---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: default
spec:
  encryptedData:
    admin_password: AgBEV7Z0ii5iSUgSdR/dmf8vTOwwZkI/jxivgRy5DQlEX1lE/sgGchSapFvLfy/7bvwQ4s2NH6fiqjpfeh0hkMhOrtd3ExENKFVxdDAs0LVdrvsMhf/p52H5lSeatXjyl4qt8rV7oCaK/O99su/3bbdvsUZ/y0EF6WUhc1MsHww/uE87vUSQC9ZJ0+Rj3RYVFjDSl2p1LtZ1UsxLOJzH0fIMkYGeLpOfj2y0XceMYzeXj7Q57usocC73/rN6E5dbPuM/GKwFCDEvKwG1aVoFgsVaYUcXjlGeKrUOHHYY0Q6pjLVrdEE88ffxaWSGb1nHc8N3MKjMJVTDfUgDA8Ily/Iv0dm95o/pYPPooQ9TScURdoKmLDvCz5+4FkOilBWg+lsQFcVmeKjeeBkW1EDpATB3Rrv1LRoYXuBWxw5QRKRpt+X4fkq+LMg3K6OOOttAjilBnIAuTsjhuf747MXjfklQVaY6CY2i7/wLcdoouVSPjQiI0NJHG4f+3FOdckarEAu7XwScVnHkQFfgzOdNdCbKZkTh/gbmbQdz0ATSnow/0/4JzZlVSCMahRF2oYLC5VCDdgzpCPg3HhS5D93SSk8RcBM27aTZxdVxY0iVWtouUjt2hxk2LxPENTym+Z1k0w3SkiTWtheNGYGZffykgGqvT4oyJdsbp86GF8fpM4DlEuCrPrvppecnm0yOSDJu7CtqSZR5qQ==
  template:
    metadata:
      name: grafana-secret
      namespace: default
    type: Opaque
