---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: myapp-secret
  namespace: default
spec:
  encryptedData:
    .env: AgAzau+cCnSoIEgXOzUPOMbnZuyQrvyis+tgEgMXAKcrp52w+GCR8CPfti4V3SthwQov/tcHDxCWCPA0i/qJf0KY2eQba7hZ87xkm2JKpYYb53+Jg9mDNnwn5eHeifNoiNj1XYL/h9eVQqpg4mED7HZ8an1jKK2HyJpevriUCdwwe/uUZpTMp2Mo7M8KUnb3YKOmPULnaZzhLhB6Rz8qVPBHzUaNoo8fbod0dFaw8+jjblZ2msj3OnvPa3YU7lkKbkx9wU5JMJsVIWVR2jVqem9iCU0cXGdYVeoRa4iY+kWt+TGBkYEeHm8h3m0lDTkPTQ05hwERIC9Tx0KQJsdqkimDh+NpX9dmmHVlylwa9vtGGQYP/+dpTaP9iGcBoncBy1h8bt+4YL70kr/BeTOhv7Psl1/7kLrAvytcmZcVvz7QEewrKyikjtSjuIpiPwKUUPJDQQsoy22zkFK4xYbq+GrutzRXSGPsSk0lFmSdtkyRs1n0bv9ErNA73S4rHiGdKyMQGO9OuRsN3kgtP1ZOMGnH4Bb2e2BiNEYQH28KD6EoaPBDucM57USraUBdgf2V0It/Dn/4GkNtqJR/cHEMY9OiyAtMquAP7ODsXK1VgtM+v8b6ArB/lmQdnsn+MUc7nKoa0vYC0BVdRDzB2S0Gxo4X8sOuxUcGqrhudUIKpxXH0/1uyUeLkudzhEJpOXBDrrtkQZ+7NpCOZfIUfuCtIhmoBb2r10jFKnT+4QcfBUrj9duMa6yJ/Q7KYMSpatav
  template:
    metadata:
      name: myapp-secret
      namespace: default
    type: Opaque
